project_id = "portpass"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = false

[storage]
enabled = false

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[auth.email]
enable_signup = false

[realtime]
enabled = false

[edge_runtime]
enabled = false

[analytics]
enabled = false
