import { WEEKDAYS, generateWeeklySessionDates } from "@/lib/scheduling";
import { ageLabel } from "@/lib/futprepClasses";
import { slugify } from "@/lib/slug";
import { getSupabaseAdmin, throwIfSupabaseError } from "./supabase";

export type FutprepProgramInput = {
  name: string;
  ageMin: number;
  ageMax: number;
  coed: boolean;
  locationName: string;
  locationAddress: string;
  dayOfWeek: string;
  startTime: string;
  endTime: string;
  capacity: number;
  termName: string;
  termStartDate: string;
  termEndDate: string;
  breakDates: string[];
  weeklyFeeCents: number;
  termFeeCents: number;
  registrationFeeCents: number;
  // Brief 06 v2: a holiday camp runs every weekday between the term dates
  // (its days are generated by the database trigger on program_terms),
  // is paid in full (termFeeCents is the camp fee) and may close
  // registration at a set time.
  programType?: "term" | "camp" | "contract";
  registrationClosesAt?: string | null;
  whatToBring?: string | null;
  // Brief 13: a site from the locations table (else locationName is used),
  // and for a school contract, who pays and how.
  locationId?: number | null;
  contractClient?: string | null;
  contractFeeCents?: number | null;
  contractBilling?: "per_session" | "per_term" | null;
};

export type FutprepSite = { id: number; name: string; area: string | null };

// Futprep's sites (brief 13): LCIS Lower Campus, Meridian School, Winton
// (Out East), St Andrew's School, and any added since.
export async function listFutprepSites(): Promise<FutprepSite[]> {
  const db = getSupabaseAdmin();
  const organizationId = await futprepOrganizationId();
  const { data, error } = await db.from("locations").select("id,name,map_label").eq("organization_id", organizationId).eq("active", true).order("name");
  throwIfSupabaseError(error, "Could not load Futprep sites");
  return (data ?? []).map((row) => ({ id: Number(row.id), name: String(row.name), area: (row.map_label as string | null) ?? null }));
}

export type FutprepProgramSummary = {
  id: number;
  slug: string;
  name: string;
  ageMin: number;
  ageMax: number;
  // Brief 12: "1½–3" (months win over whole years when set).
  ageLabel: string;
  coed: boolean;
  location: string;
  dayOfWeek: string;
  startTime: string;
  endTime: string | null;
  capacity: number;
  active: boolean;
  // Brief 27 (A): an unlisted program (is_public = false) is hidden from
  // parents but still here for staff; the note is staff-only too.
  isPublic: boolean;
  staffNote: string | null;
  // Who it is for (brief 18, D3).
  audience: "children" | "adults" | "mixed";
  // Brief 13: the kind of program, its site, and a school contract's terms.
  programType: "term" | "camp" | "contract";
  siteName: string | null;
  contractClient: string | null;
  contractFeeCents: number | null;
  contractBilling: "per_session" | "per_term" | null;
  term: {
    id: number;
    name: string;
    startDate: string;
    endDate: string;
    breakDates: string[];
    weeklyFeeCents: number;
    termFeeCents: number;
    registrationFeeCents: number;
  } | null;
  registered: number;
  spotsRemaining: number | null;
};

async function uniqueSlug(base: string) {
  const db = getSupabaseAdmin();
  let candidate = base;
  let attempt = 1;
  while (attempt < 50) {
    const { data, error } = await db
      .from("programs")
      .select("id")
      .eq("slug", candidate)
      .maybeSingle();
    throwIfSupabaseError(error, "Could not verify program slug");
    if (!data) return candidate;
    attempt += 1;
    candidate = `${base}-${attempt}`;
  }
  throw new Error("Could not generate a unique program slug");
}

export async function futprepOrganizationId(): Promise<number> {
  const db = getSupabaseAdmin();

  const { data: bySlug, error: slugError } = await db
    .from("organizations")
    .select("id")
    .eq("slug", "futprep")
    .maybeSingle();
  throwIfSupabaseError(slugError, "Could not locate Futprep organization");
  if (bySlug) return Number(bySlug.id);

  // Fallback for any environment where the slug backfill
  // (supabase/migrations/202609092002_organizations_slug_theme.sql) hasn't
  // run yet, or the organization predates it.
  const { data, error } = await db
    .from("organizations")
    .select("id")
    .or("name.ilike.%futprep%,name.ilike.%footprep%")
    .order("id", { ascending: true })
    .limit(1)
    .maybeSingle();
  throwIfSupabaseError(error, "Could not locate Futprep organization");
  if (!data) throw new Error("FUTPREP_ORG_NOT_FOUND");
  return Number(data.id);
}

// `forOrganizationId` (brief 18, D4): any business's programmes; without
// it, Futprep's, as before.
export async function listFutprepPrograms(forOrganizationId?: number): Promise<FutprepProgramSummary[]> {
  const db = getSupabaseAdmin();
  const organizationId = forOrganizationId ?? (await futprepOrganizationId());

  const { data: programs, error: programsError } = await db
    .from("programs")
    .select("id,slug,name,age_min,age_max,age_min_months,age_max_months,coed,location,day_of_week,start_time,end_time,capacity,active,is_public,staff_note,audience,program_type,location_id,contract_client,contract_fee_cents,contract_billing,locations(name)")
    .eq("organization_id", organizationId)
    .order("id", { ascending: true });
  throwIfSupabaseError(programsError, "Could not load Futprep programs");

  const output: FutprepProgramSummary[] = [];
  const programList = programs ?? [];
  if (programList.length === 0) return output;

  // Two queries for every program, not two per program (speed brief, 29
  // Sept, 1.3): the latest active term per program and the active
  // registrations, counted here. Same shape as getFutprepAvailability.
  const programIds = programList.map((program) => program.id);
  const [{ data: terms, error: termsError }, { data: activeRegistrations, error: countError }] = await Promise.all([
    db
      .from("program_terms")
      .select("id,program_id,name,start_date,end_date,break_dates,weekly_fee_cents,term_fee_cents,registration_fee_cents")
      .in("program_id", programIds)
      .eq("active", true)
      .order("start_date", { ascending: false }),
    db
      .from("registrations")
      .select("program_id,term_id")
      .in("program_id", programIds)
      .in("registration_status", ["pending_details", "pending", "confirmed"]),
  ]);
  throwIfSupabaseError(termsError, "Could not load program term");
  throwIfSupabaseError(countError, "Could not count registrations");

  type TermRow = NonNullable<typeof terms>[number];
  const latestTermByProgram = new Map<number, TermRow>();
  for (const term of terms ?? []) {
    if (!latestTermByProgram.has(Number(term.program_id))) latestTermByProgram.set(Number(term.program_id), term);
  }
  const registeredByKey = new Map<string, number>();
  for (const row of activeRegistrations ?? []) {
    const key = `${row.program_id}:${row.term_id}`;
    registeredByKey.set(key, (registeredByKey.get(key) ?? 0) + 1);
  }

  for (const program of programList) {
    const term = latestTermByProgram.get(Number(program.id)) ?? null;
    const registered = term ? registeredByKey.get(`${program.id}:${term.id}`) ?? 0 : 0;
    const spotsRemaining: number | null = term ? Math.max(0, Number(program.capacity) - registered) : null;

    output.push({
      id: Number(program.id),
      slug: program.slug,
      name: program.name,
      ageMin: Number(program.age_min),
      ageMax: Number(program.age_max),
      ageLabel: ageLabel({ ageMin: Number(program.age_min), ageMax: Number(program.age_max), ageMinMonths: program.age_min_months ?? null, ageMaxMonths: program.age_max_months ?? null }),
      coed: Boolean(program.coed),
      location: program.location,
      dayOfWeek: program.day_of_week,
      startTime: program.start_time,
      endTime: program.end_time ?? null,
      capacity: Number(program.capacity),
      active: Boolean(program.active),
      isPublic: program.is_public !== false,
      staffNote: (program.staff_note as string | null)?.trim() || null,
      audience: program.audience === "adults" || program.audience === "mixed" ? program.audience : "children",
      programType: program.program_type === "camp" ? "camp" : program.program_type === "contract" ? "contract" : "term",
      siteName: (program.locations as unknown as { name: string } | null)?.name ?? null,
      contractClient: program.contract_client ?? null,
      contractFeeCents: program.contract_fee_cents === null || program.contract_fee_cents === undefined ? null : Number(program.contract_fee_cents),
      contractBilling: program.contract_billing === "per_term" ? "per_term" : program.contract_billing === "per_session" ? "per_session" : null,
      term: term
        ? {
            id: Number(term.id),
            name: term.name,
            startDate: term.start_date,
            endDate: term.end_date,
            breakDates: (term.break_dates ?? []) as string[],
            weeklyFeeCents: Number(term.weekly_fee_cents),
            termFeeCents: Number(term.term_fee_cents),
            registrationFeeCents: Number(term.registration_fee_cents),
          }
        : null,
      registered,
      spotsRemaining,
    });
  }

  return output;
}

export async function setFutprepProgramActive(id: number, active: boolean) {
  const db = getSupabaseAdmin();
  const { error } = await db.from("programs").update({ active }).eq("id", id);
  throwIfSupabaseError(error, "Could not update the program.");
}

// `scope` (brief 18, D4): the business the programme is for and who it is
// for; without it, a Futprep children's programme, as before.
export async function createFutprepProgram(input: FutprepProgramInput, scope?: { organizationId: number; audience: "children" | "adults" | "mixed" }) {
  const db = getSupabaseAdmin();
  const now = new Date().toISOString();
  const organizationId = scope?.organizationId ?? (await futprepOrganizationId());

  if (input.ageMin < 0 || input.ageMax < input.ageMin) throw new Error("INVALID_AGE_RANGE");
  if (input.capacity <= 0) throw new Error("INVALID_CAPACITY");
  const isCamp = input.programType === "camp";
  const isContract = input.programType === "contract";
  if (!isCamp && !WEEKDAYS.includes(input.dayOfWeek)) throw new Error("INVALID_DAY");
  if (isContract && (!input.contractClient?.trim() || !Number.isInteger(input.contractFeeCents) || (input.contractFeeCents ?? -1) < 0 || !input.contractBilling)) {
    throw new Error("INVALID_CONTRACT");
  }
  if (new Date(`${input.termEndDate}T12:00:00Z`) < new Date(`${input.termStartDate}T12:00:00Z`)) {
    throw new Error("INVALID_TERM_DATES");
  }

  // A chosen site wins; otherwise the typed location becomes (or matches) a
  // site, so every new program has one (brief 13).
  let locationName = input.locationName;
  let locationId: number | null = null;
  if (input.locationId) {
    const { data: site, error: siteError } = await db.from("locations").select("id,name").eq("id", input.locationId).eq("organization_id", organizationId).maybeSingle();
    throwIfSupabaseError(siteError, "Could not load the site");
    if (!site) throw new Error("INVALID_SITE");
    locationName = String(site.name);
    locationId = Number(site.id);
  } else {
    const { data: site, error: locationError } = await db.from("locations").upsert(
      {
        organization_id: organizationId,
        name: input.locationName,
        address: input.locationAddress || input.locationName,
        map_label: input.locationName,
        active: true,
        created_at: now,
      },
      { onConflict: "organization_id,name" },
    ).select("id").single();
    throwIfSupabaseError(locationError, "Could not save the program location");
    locationId = site ? Number(site.id) : null;
  }

  const slug = await uniqueSlug(slugify(input.name));

  const { data: program, error: programError } = await db
    .from("programs")
    .insert({
      organization_id: organizationId,
      slug,
      name: input.name.trim(),
      age_min: input.ageMin,
      age_max: input.ageMax,
      coed: input.coed,
      location: locationName,
      location_id: locationId,
      day_of_week: isCamp ? "Weekdays" : input.dayOfWeek,
      start_time: input.startTime,
      end_time: input.endTime || null,
      capacity: input.capacity,
      program_type: isCamp ? "camp" : isContract ? "contract" : "term",
      audience: scope?.audience ?? "children",
      // A school contract is never public or registrable (the database
      // forces this too).
      is_public: !isContract,
      contract_client: isContract ? input.contractClient!.trim() : null,
      contract_fee_cents: isContract ? input.contractFeeCents : null,
      contract_billing: isContract ? input.contractBilling : null,
      active: true,
      created_at: now,
    })
    .select("id")
    .single();
  throwIfSupabaseError(programError, "Could not create the program");
  if (!program) throw new Error("Could not create the program");

  const programId = Number(program.id);

  const { data: term, error: termError } = await db
    .from("program_terms")
    .insert({
      program_id: programId,
      name: input.termName.trim(),
      start_date: input.termStartDate,
      end_date: input.termEndDate,
      break_dates: input.breakDates,
      weekly_fee_cents: input.weeklyFeeCents,
      term_fee_cents: input.termFeeCents,
      registration_fee_cents: input.registrationFeeCents,
      daily_start_time: isCamp ? input.startTime : null,
      daily_end_time: isCamp ? input.endTime || null : null,
      registration_closes_at: input.registrationClosesAt ?? null,
      what_to_bring: input.whatToBring?.trim() || null,
      active: true,
      created_at: now,
    })
    .select("id")
    .single();
  throwIfSupabaseError(termError, "Could not create the program term");
  if (!term) throw new Error("Could not create the program term");

  const termId = Number(term.id);
  // A camp's days were generated by the database trigger when the term
  // row went in (public.generate_camp_sessions).
  const sessionDates = isCamp ? [] : generateWeeklySessionDates({
    startDate: input.termStartDate,
    endDate: input.termEndDate,
    dayOfWeek: input.dayOfWeek,
    breakDates: input.breakDates,
  });
  const sessions: Array<Record<string, unknown>> = sessionDates.map((sessionDate) => ({
    program_id: programId,
    term_id: termId,
    session_date: sessionDate,
    start_time: input.startTime,
    location: locationName,
    status: "scheduled",
    created_at: now,
  }));

  if (sessions.length) {
    const { error: sessionError } = await db.from("sessions").upsert(sessions, {
      onConflict: "program_id,term_id,session_date",
    });
    throwIfSupabaseError(sessionError, "Could not schedule program sessions");
  }

  if (isCamp) {
    const { count } = await db.from("sessions").select("id", { count: "exact", head: true }).eq("program_id", programId).eq("term_id", termId);
    return { id: programId, slug, sessionsCreated: Number(count ?? 0) };
  }
  return { id: programId, slug, sessionsCreated: sessions.length };
}
