-- Futprep coach directory, availability, and private-session workflow.
-- Run in Supabase SQL editor after deploying the matching PortPass code.

create table if not exists public.coach_profiles (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  slug text not null,
  display_name text not null,
  position_title text not null default 'Coach',
  member_type text not null default 'coach'
    check (member_type in ('coach','relations','admin')),
  bio text not null default '',
  licenses text[] not null default '{}',
  played_at text[] not null default '{}',
  favorite_player text,
  favorite_team text,
  photo_url text,
  intro_video_url text,
  testimonial_quote text,
  testimonial_name text,
  public_visible boolean not null default true,
  bookable boolean not null default true,
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(organization_id,slug)
);

create table if not exists public.coach_availability (
  id bigint generated by default as identity primary key,
  coach_id bigint not null references public.coach_profiles(id) on delete cascade,
  availability_date date not null,
  start_time text not null,
  end_time text not null,
  status text not null default 'available'
    check (status in ('available','blocked','booked')),
  location text not null default '',
  note text not null default '',
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(coach_id,availability_date,start_time,end_time)
);

create index if not exists coach_availability_date_idx
  on public.coach_availability(availability_date);

create table if not exists public.private_session_requests (
  id bigint generated by default as identity primary key,
  reference_code text not null unique,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  preferred_coach_id bigint references public.coach_profiles(id) on delete set null,
  assigned_coach_id bigint references public.coach_profiles(id) on delete set null,
  referred_from_coach_id bigint references public.coach_profiles(id) on delete set null,
  request_type text not null default 'private_lesson'
    check (request_type in ('private_lesson','birthday')),
  parent_name text not null,
  parent_email text not null,
  parent_phone text not null,
  child_name text not null,
  child_age integer not null check (child_age between 1 and 18),
  requested_date date not null,
  requested_start_time text not null,
  duration_minutes integer not null default 60
    check (duration_minutes in (30,45,60,90,120)),
  location_preference text not null default '',
  session_goal text not null default '',
  notes text not null default '',
  status text not null default 'pending'
    check (status in ('pending','accepted','declined','referred','cancelled','completed')),
  decline_reason text,
  referral_note text,
  parent_notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists private_session_requests_status_idx
  on public.private_session_requests(status);
create index if not exists private_session_requests_date_idx
  on public.private_session_requests(requested_date);

create table if not exists public.private_session_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.private_session_requests(id) on delete cascade,
  actor_account text not null,
  action text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);

alter table public.coach_profiles enable row level security;
alter table public.coach_availability enable row level security;
alter table public.private_session_requests enable row level security;
alter table public.private_session_events enable row level security;

revoke all on table public.coach_profiles from anon, authenticated;
revoke all on table public.coach_availability from anon, authenticated;
revoke all on table public.private_session_requests from anon, authenticated;
revoke all on table public.private_session_events from anon, authenticated;

-- Seed the current Futprep team without inventing credentials, playing history, or licenses.
with futprep as (
  select id
  from public.organizations
  where lower(name) like '%futprep%' or lower(name) like '%footprep%'
  order by id
  limit 1
)
insert into public.coach_profiles (
  organization_id,slug,display_name,position_title,member_type,bio,public_visible,bookable,active,sort_order
)
select id,'alexander-thompson','Coach Alexander Thompson','CEO · Coach','coach',
  'Coach profile details coming soon.',true,true,true,10 from futprep
union all
select id,'ronaldo-greene','Coach Ronaldo Greene','Coach','coach',
  'Coach profile details coming soon.',true,true,true,20 from futprep
union all
select id,'antonio-beckford-jr','Coach Antonio Beckford Jr','Coach Bex · Coach','coach',
  'Coach profile details coming soon.',true,true,true,30 from futprep
union all
select id,'keione-rayside','Keione Rayside (Kiki)','Relations · Brand & Public Experience','relations',
  'Kiki leads how Futprep communicates, presents itself, and builds relationships with families and the public.',true,false,true,40 from futprep
on conflict (organization_id,slug) do nothing;
