-- Futprep staff operations, restored: session_plans and staff_work_logs.
--
-- 202609010002 makes these two tables, and a fresh stack (CI) has them.
-- The project's own database did not (checked on 5 Oct 2026: 74 public
-- tables, neither of these, neither index), so the coach's session plan
-- and work-hours tools rendered empty and every save answered "needs the
-- new PortPass database update", while CI stayed green. 202610180001
-- (rls_policies) noticed and skipped them with a notice, so the restrictive
-- deny policy it gives every owner-only table is attached here as well.
--
-- Every statement is idempotent: on a stack that has the tables and the
-- policies already, this file changes nothing.

create table if not exists public.session_plans (
  id bigint generated by default as identity primary key,
  session_id bigint not null unique references public.sessions(id) on delete cascade,
  title text not null default '',
  plan_text text not null default '',
  parent_note text not null default '',
  attachment_url text not null default '',
  updated_by text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists session_plans_session_idx
  on public.session_plans(session_id);

create table if not exists public.staff_work_logs (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  staff_name text not null,
  work_date date not null,
  start_time text not null default '',
  end_time text not null default '',
  hours numeric(5,2) not null default 0 check (hours >= 0 and hours <= 24),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique(session_id,staff_name)
);

create index if not exists staff_work_logs_session_idx
  on public.staff_work_logs(session_id);

-- Owner-only, as 202610180001 classes them: no browser role may read or
-- write a row. The grants are revoked, and a RESTRICTIVE policy that is
-- always false is attached for anon and authenticated.
do $$
declare
  t text;
begin
  foreach t in array array['session_plans', 'staff_work_logs'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('drop policy if exists %I on public.%I', t || '_browser_roles_denied', t);
    execute format(
      'create policy %I on public.%I as restrictive for all to anon, authenticated using (false) with check (false)',
      t || '_browser_roles_denied', t
    );
  end loop;
end $$;
