-- Shared Futprep notes inbox for product ideas, operations, leads, brand, content and issues.

create table if not exists public.futprep_notes (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  title text not null,
  body text not null,
  category text not null default 'idea'
    check (category in ('product','operations','content','lead','brand','issue','idea')),
  priority text not null default 'normal'
    check (priority in ('normal','high')),
  status text not null default 'inbox'
    check (status in ('inbox','actioned','archived')),
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists futprep_notes_org_status_idx
  on public.futprep_notes(organization_id,status,created_at desc);

alter table public.futprep_notes enable row level security;
revoke all on table public.futprep_notes from anon, authenticated;

with futprep as (
  select id
  from public.organizations
  where lower(name) like '%futprep%' or lower(name) like '%footprep%'
  order by id
  limit 1
)
insert into public.futprep_notes
  (organization_id,title,body,category,priority,status,created_by)
select id,
  'Coach marketplace + private sessions',
  'Build coaches, availability, private lessons, birthdays, accept/decline/referral flow, and parent confirmation as one connected Futprep operations system.',
  'product','high','inbox','Adon + Antonio'
from futprep
union all
select id,
  'Futprep brand revamp',
  'Re-establish how Futprep is presented publicly. Coach profiles, player journeys, testimonials, photos and videos should double as a reusable content bank for the relaunch.',
  'brand','high','inbox','Adon + Antonio'
from futprep
union all
select id,
  'Renegades FC opportunity',
  'Potential PortPass + consulting lead. Renegades reportedly needs a rebrand, new coaches and more youth recruitment. There are also privately reported organizational challenges; verify details before any external use or outreach.',
  'lead','high','inbox','Adon'
from futprep
union all
select id,
  'Carvmindset / Jason',
  'Warm lead. Antonio knows Jason from playing against him in the Bahamas soccer league, and both previously coached for Renegades. Jason is CEO of Carvmindset. Awaiting links/details for deeper research and an outreach strategy.',
  'lead','high','inbox','Antonio'
from futprep
union all
select id,
  'The Beckfords consulting position',
  'Position Antonio and Adon as practical consultants who identify inefficiencies inside companies, design the fix, and help execute the solution rather than only giving advice.',
  'idea','high','inbox','Antonio + Adon'
from futprep;
