-- PortPass production schema for Supabase/Postgres.
-- All application reads and writes currently go through trusted Next.js server routes
-- using the server-only Supabase service-role key. RLS is enabled with no public
-- policies so anon/authenticated clients cannot read child, health, emergency,
-- registration, or payment records directly.

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  organization_name text not null,
  contact_person text not null,
  email text not null,
  phone text not null,
  activity_type text not null,
  main_location text not null,
  player_count text not null,
  help_needed text not null,
  description text not null,
  status text not null default 'submitted'
    check (status in ('submitted','approved','rejected')),
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists applications_status_idx
  on public.applications(status);

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  application_id bigint not null unique
    references public.applications(id) on delete restrict,
  name text not null,
  primary_contact text not null,
  email text not null,
  phone text not null,
  activity_type text not null,
  main_location text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  organization_id bigint references public.organizations(id) on delete cascade,
  slug text not null unique,
  name text not null,
  age_min integer not null check (age_min >= 0),
  age_max integer not null check (age_max >= age_min),
  coed boolean not null default true,
  location text not null,
  day_of_week text not null,
  start_time text not null,
  capacity integer not null check (capacity > 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists programs_organization_idx
  on public.programs(organization_id);

create table if not exists public.program_terms (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs(id) on delete cascade,
  name text not null,
  start_date date not null,
  end_date date not null,
  break_dates date[] not null default '{}',
  weekly_fee_cents integer not null check (weekly_fee_cents >= 0),
  term_fee_cents integer not null check (term_fee_cents >= 0),
  registration_fee_cents integer not null default 0
    check (registration_fee_cents >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(program_id,name),
  check (end_date >= start_date)
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  organization_id bigint not null
    references public.organizations(id) on delete cascade,
  name text not null,
  address text not null,
  map_label text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(organization_id,name)
);

create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  organization_id bigint not null
    references public.organizations(id) on delete cascade,
  name text not null,
  role text not null,
  email text,
  responsibilities text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(organization_id,name,role)
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs(id) on delete cascade,
  term_id bigint not null references public.program_terms(id) on delete cascade,
  session_date date not null,
  start_time text not null,
  location text not null,
  status text not null default 'scheduled'
    check (status in ('scheduled','cancelled','completed')),
  created_at timestamptz not null default now(),
  unique(program_id,term_id,session_date)
);

create index if not exists sessions_date_idx
  on public.sessions(session_date);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  reference_code text not null unique,
  organization_id bigint references public.organizations(id) on delete cascade,
  program_id bigint not null references public.programs(id) on delete restrict,
  term_id bigint not null references public.program_terms(id) on delete restrict,

  parent_name text not null,
  parent_email text not null,
  parent_phone text not null,
  relationship text not null,

  child_name text not null,
  child_dob date not null,
  gender text not null,

  emergency_contact_name text not null,
  emergency_contact_phone text not null,
  allergies text not null default '',
  medical_conditions text not null default '',
  medications text not null default '',
  special_needs text not null default '',
  authorized_pickup text not null,
  additional_notes text not null default '',

  photo_consent text not null check (photo_consent in ('yes','no')),
  payment_frequency text not null
    check (payment_frequency in ('weekly','term')),
  payment_method text not null
    check (payment_method in ('cash','bank_transfer')),
  amount_due_cents integer not null check (amount_due_cents >= 0),

  registration_status text not null default 'pending'
    check (registration_status in ('pending','confirmed','cancelled')),
  payment_status text not null default 'pending'
    check (payment_status in ('pending','partial','paid','overdue','waived')),

  consent_version text not null,
  consent_accepted boolean not null,
  consent_at timestamptz not null,
  signature_name text not null,
  submitted_at timestamptz not null default now()
);

create index if not exists registrations_program_term_idx
  on public.registrations(program_id,term_id);
create index if not exists registrations_parent_email_idx
  on public.registrations(lower(parent_email));
create index if not exists registrations_organization_idx
  on public.registrations(organization_id);
create index if not exists registrations_payment_status_idx
  on public.registrations(payment_status);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  registration_id bigint not null
    references public.registrations(id) on delete cascade,
  amount_cents integer not null check (amount_cents > 0),
  method text not null check (method in ('cash','bank_transfer')),
  status text not null default 'received'
    check (status in ('received','voided','refunded')),
  recorded_by text,
  note text not null default '',
  received_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists payments_registration_idx
  on public.payments(registration_id);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  registration_id bigint not null
    references public.registrations(id) on delete cascade,
  session_id bigint not null references public.sessions(id) on delete cascade,
  status text not null check (status in ('present','absent','excused')),
  marked_by text,
  marked_at timestamptz not null default now(),
  unique(registration_id,session_id)
);

create index if not exists attendance_session_idx
  on public.attendance(session_id);

-- Defense in depth: no browser/client can directly query these tables.
-- The service-role key used only by PortPass server routes bypasses RLS.
alter table public.applications enable row level security;
alter table public.organizations enable row level security;
alter table public.programs enable row level security;
alter table public.program_terms enable row level security;
alter table public.locations enable row level security;
alter table public.staff_members enable row level security;
alter table public.sessions enable row level security;
alter table public.registrations enable row level security;
alter table public.payments enable row level security;
alter table public.attendance enable row level security;

revoke all on table public.applications from anon, authenticated;
revoke all on table public.organizations from anon, authenticated;
revoke all on table public.programs from anon, authenticated;
revoke all on table public.program_terms from anon, authenticated;
revoke all on table public.locations from anon, authenticated;
revoke all on table public.staff_members from anon, authenticated;
revoke all on table public.sessions from anon, authenticated;
revoke all on table public.registrations from anon, authenticated;
revoke all on table public.payments from anon, authenticated;
revoke all on table public.attendance from anon, authenticated;
