-- Futprep staff operations: coaching plans and work-hour tracking.

create table if not exists public.session_plans (
  id bigint generated by default as identity primary key,
  session_id bigint not null unique references public.sessions(id) on delete cascade,
  title text not null default '',
  plan_text text not null default '',
  parent_note text not null default '',
  attachment_url text not null default '',
  updated_by text not null default '',
  updated_at timestamptz not null default now()
);

create index if not exists session_plans_session_idx
  on public.session_plans(session_id);

create table if not exists public.staff_work_logs (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  staff_name text not null,
  work_date date not null,
  start_time text not null default '',
  end_time text not null default '',
  hours numeric(5,2) not null default 0 check (hours >= 0 and hours <= 24),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique(session_id,staff_name)
);

create index if not exists staff_work_logs_session_idx
  on public.staff_work_logs(session_id);

alter table public.session_plans enable row level security;
alter table public.staff_work_logs enable row level security;

revoke all on table public.session_plans from anon, authenticated;
revoke all on table public.staff_work_logs from anon, authenticated;
